export type CapabilityCode =
  | 'SUBMIT_OWN_CLAIM'
  | 'VIEW_OWN_CLAIM'
  | 'VIEW_ANY_CLAIM'
  | 'REQUEST_MORE_INFO'
  | 'OVERRIDE_AI_DECISION'
  | 'APPROVE_CLAIM_WITHIN_ADJUSTER_DOA'
  | 'APPROVE_CLAIM_WITHIN_SR_DOA'
  | 'APPROVE_CLAIM_ABOVE_SR_DOA'
  | 'SUBMIT_SURVEYOR_REPORT'
  | 'FILE_STR_TO_FIU_IND'
  | 'INITIATE_GRIEVANCE'
  | 'RESOLVE_GRIEVANCE'
  | 'REOPEN_CLOSED_CLAIM'
  | 'AUTHORISE_PAYOUT_NEW_BANK_ACCOUNT'
  | 'ACCESS_FORENSIC_ARTIFACTS'
  | 'CHANGE_CONFIDENCE_THRESHOLDS_UI'
  | 'PROPOSE_THRESHOLD_CHANGE'
  | 'APPROVE_THRESHOLD_CHANGE'
  | 'MANAGE_USER_ROLES'
  | 'MANAGE_DOA_MATRIX'
  | 'EXECUTE_RIGHT_TO_ERASURE'
  | 'REQUEST_RIGHT_TO_ERASURE'
  | 'INVOKE_AI_PIPELINES';

export type PermissionScope =
  | 'GRANTED'
  | 'READ_ONLY'
  | 'ASSIGNMENT_RESTRICTED'
  | 'FOUR_EYE_REQUIRED';

export const PERMISSION_SCOPES: PermissionScope[] = [
  'GRANTED', 'READ_ONLY', 'ASSIGNMENT_RESTRICTED', 'FOUR_EYE_REQUIRED'
];

export interface PermissionResponse {
  id: string;
  capability: CapabilityCode;
  scope: PermissionScope;
  description?: string;
}
